
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wojciechkuczer
 */
public class GuessMyWord extends javax.swing.JFrame {

    /**
     * Creates new form GuessMyWord
     */
    private int counter = 10;
    private String misteryWord;
    private String correct;
    
    //program takes original word from previous JFrame and sets jumble word
    public void setMisteryWord(String text){
        this.misteryWord = text;
        correct = misteryWord;
        lblMisteryWord.setText(jumbleString());
    }
    
    //method to mix letters in original word
    private String jumbleString(){
        String jumble = "";
        while(misteryWord.length() !=0){
            int position = (int)(Math.random() * misteryWord.length());
            jumble += misteryWord.charAt(position);
            misteryWord = misteryWord.substring(0,position) + misteryWord.substring(position + 1);
        }
        return jumble;
    }
    
    
    public GuessMyWord() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
   
    //method to display whether user entered correct or incorrect answer
    private void guessEntere(){
        if(correct.equals(txtGuessWord.getText()) && (counter > 1)){
            lblGoodBadGuess.setText("You WON!!! \"" + txtGuessWord.getText() + "\" is a correct answer");
            counter--;
            lblCounter.setText("" + (counter));
            btnGuess.setEnabled(false);
            btnGiveUp.setEnabled(false);
        }else if(counter == 1){
            lblGoodBadGuess.setText("You LOST!!! \"" + correct + "\" is a correct answer");
            lblCounter.setText("" + (--counter));
            btnGuess.setEnabled(false);
            btnGiveUp.setEnabled(false);
        }else{
            lblGoodBadGuess.setText("Try again \"" + txtGuessWord.getText() + "\" is a wrong answer");
            counter--;
            lblCounter.setText("" + (counter));
        }
    }
    
    
    //method to reset game and start again
    private void playAgain(){
        StartGuessMyWord newGame = new StartGuessMyWord();
        newGame.setVisible(true);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        WindowEvent windowEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowEvent);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEnterGuess = new javax.swing.JLabel();
        txtGuessWord = new javax.swing.JTextField();
        lblGoodBadGuess = new javax.swing.JLabel();
        btnGuess = new javax.swing.JButton();
        btnGiveUp = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        lblCounter = new javax.swing.JLabel();
        lblMisteryWord = new javax.swing.JLabel();
        lblTop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblEnterGuess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnterGuess.setText("Enter Your Guess");

        txtGuessWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGuessWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGuessWordKeyTyped(evt);
            }
        });

        lblGoodBadGuess.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblGoodBadGuess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoodBadGuess.setText("Try to guess correct answer in 10 attempts");

        btnGuess.setText("GUESS");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnGiveUp.setText("GIVE UP");
        btnGiveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveUpActionPerformed(evt);
            }
        });

        btnPlayAgain.setText("PLAY AGAIN");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        lblCounter.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounter.setText("10");

        lblMisteryWord.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblMisteryWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTop.setText("What's that word");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGoodBadGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPlayAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGiveUp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnterGuess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGuessWord)
                    .addComponent(lblMisteryWord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTop, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMisteryWord, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGuessWord, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGoodBadGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiveUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        // TODO add your handling code here:
        playAgain();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnGiveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveUpActionPerformed
        // TODO add your handling code here:
        lblGoodBadGuess.setText("The correct answer is: " + correct);
        btnGuess.setEnabled(false);
        btnGiveUp.setEnabled(false);
    }//GEN-LAST:event_btnGiveUpActionPerformed

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        // TODO add your handling code here:
        guessEntere();
    }//GEN-LAST:event_btnGuessActionPerformed

    private void txtGuessWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGuessWordKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGuessWordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessMyWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessMyWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessMyWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessMyWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessMyWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiveUp;
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JLabel lblEnterGuess;
    private javax.swing.JLabel lblGoodBadGuess;
    private javax.swing.JLabel lblMisteryWord;
    private javax.swing.JLabel lblTop;
    private javax.swing.JTextField txtGuessWord;
    // End of variables declaration//GEN-END:variables
}
